//
//  StyleKitName.h
//  ProjectName
//
//  Created by AuthorName on 14-9-19.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitName : NSObject

// Drawing Methods
+ (void)drawRedBubbleWithFrame: (CGRect)frame;
+ (void)drawPlaceBubble:(NSString*)place color:(UIColor *)color;

@end
