//
//  StyleKitName.m
//  ProjectName
//
//  Created by AuthorName on 14-9-19.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKitName.h"


@implementation StyleKitName

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawRedBubbleWithFrame: (CGRect)frame;
{
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 0.949 green: 0.792 blue: 0.796 alpha: 1];
    UIColor* strokecolor = [UIColor colorWithRed: 0.902 green: 0.898 blue: 0.89 alpha: 1];

    //// Oval Drawing
    UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(CGRectGetMinX(frame) + 20, CGRectGetMinY(frame) + 20, 160, 160)];
    [color setFill];
    [ovalPath fill];
    [strokecolor setStroke];
    ovalPath.lineWidth = 4;
    [ovalPath stroke];
}

+ (void)drawPlaceBubble:(NSString*)place color:(UIColor *)color;
{

    //// place Drawing
    CGRect placeRect = CGRectMake(0, 0, 40, 40);
    UIBezierPath* placePath = [UIBezierPath bezierPathWithOvalInRect: placeRect];
    [color setFill];
    [placePath fill];
    {
        NSString* textContent = place;
        UIFont* placeFont = [UIFont fontWithName: @"Helvetica" size: 12];
        [UIColor.whiteColor setFill];
        [textContent drawInRect: CGRectOffset(placeRect, 0, (CGRectGetHeight(placeRect) - [textContent sizeWithFont: placeFont constrainedToSize: placeRect.size lineBreakMode: UILineBreakModeWordWrap].height) / 2) withFont: placeFont lineBreakMode: UILineBreakModeWordWrap alignment: UITextAlignmentCenter];
    }
}

@end
